name = "ygo-tools"
main = "./.cloudflare/worker.js"
compatibility_date = "2023-10-30"

# Node.js and pnpm version configuration
[build.environment]
NODE_VERSION = "22.14.0"
PNPM_VERSION = "10.7.1"

[build]
command = "pnpm run build"

[env.production]
routes = [
  { pattern = "*/*", zone_name = "ygo.tools" }
]

[env.preview]
name = "ygo-tools-preview"
routes = [
  { pattern = "*/*", zone_name = "preview.ygo.tools" }
]
